# Generated by Django 5.1.6 on 2025-02-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biometrics',
            old_name='expired_date',
            new_name='expiry_date',
        ),
    ]
